In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
np.array([1,2,3,4,5]) + 10

array([11, 12, 13, 14, 15])

In [4]:
np.array([1,2,3,4,5]).shape

(5,)

In [5]:
np.array([[4,5,6],[1,2,3]])

array([[4, 5, 6],
       [1, 2, 3]])

In [6]:
np.array([[4,5,6],[1,2,3]]).shape

(2, 3)

In [7]:
np.array([[4,5,6],[1,2,3]])[1][2]

3

In [8]:
sr = pd.Series([10,9,8,7])
sr

0    10
1     9
2     8
3     7
dtype: int64

In [9]:
sr.values

array([10,  9,  8,  7])

In [10]:
sr.index

RangeIndex(start=0, stop=4, step=1)

In [11]:
sr.shape

(4,)

In [12]:
sr[[0,2]]

0    10
2     8
dtype: int64

In [13]:
sr = pd.Series([10,9,8,7], index = ['a','b','c','d'])
sr

a    10
b     9
c     8
d     7
dtype: int64

In [14]:
sr[['c','d']]

c    8
d    7
dtype: int64

In [15]:
sr['b':'d']

b    9
c    8
d    7
dtype: int64

In [16]:
diccionario_data = {'CO':100, 'MX':200, 'AR':300}
diccionario_data

{'AR': 300, 'CO': 100, 'MX': 200}

In [17]:
diccionario_data.keys()

dict_keys(['CO', 'MX', 'AR'])

In [18]:
diccionario_data['CO']

100

In [19]:
pd.Series(diccionario_data)

CO    100
MX    200
AR    300
dtype: int64

In [20]:
pd.Series(diccionario_data, index = ['CO','MX','PE'])

CO    100.0
MX    200.0
PE      NaN
dtype: float64

In [21]:
np.nan

nan

In [22]:
np.nan * 10

nan

In [24]:
sr = pd.Series(diccionario_data, index = ['CO','MX','PE'])
sr

CO    100.0
MX    200.0
PE      NaN
dtype: float64

In [25]:
sr.isnull()

CO    False
MX    False
PE     True
dtype: bool

In [26]:
sr.isnull().any()

True

In [28]:
sr[sr.notnull()]

CO    100.0
MX    200.0
dtype: float64